language: python
python:
  - "3.7"
install:
  - pip install -r requirements.txt
branches:
  only:
    - master
env:
  - env: DJANGO_VERSION=2.0
services:
  - postgresql
script:
  - python manage.py test quizz.tests
