language: python
python:
  - "3.7"
install:
  - pip install -r requirements.txt
branches:
  only:
    - master
env:
  - env: DJANGO_SETTINGS_MODULE=good_citizen.travis
services:
  - postgresql
script:
  - python manage.py test quizz.tests
