# Generated by Django 3.0.7 on 2020-10-22 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizz', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='result',
            name='score',
            field=models.PositiveSmallIntegerField(null=True),
        ),
    ]
