# Generated by Django 3.0.7 on 2020-11-29 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizz', '0003_auto_20201121_1051'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LittleStory',
        ),
    ]
